---
- name: "Attempt to download Dell driver pack | {{ _dell_mdt_operating_system.os }} | {{ _dell_mdt_model.catalog_name }} | Attempt {{ _dell_mdt_download_retry | int + 1 }}" # noqa name[template]
  block:
    - name: "Increment retry counter | {{ _dell_mdt_operating_system.os }} | {{ _dell_mdt_model.catalog_name }} | Attempt {{ _dell_mdt_download_retry | int + 1 }}" # noqa name[template]
      ansible.builtin.set_fact:
        _dell_mdt_download_retry: "{{ _dell_mdt_download_retry | int + 1 }}"

    - name: "Set download path variable | {{ _dell_mdt_operating_system.os }} | {{ _dell_mdt_model.catalog_name }} | Attempt {{ _dell_mdt_download_retry }}" # noqa name[template]
      ansible.builtin.set_fact:
        _dell_mdt_download_path: >-
          {{ dell_mdt_temp_directory_path }}\{{ _dell_mdt_operating_system.os }}\{{ _dell_mdt_model.catalog_name }}

    - name: "Create temporary directory | {{ _dell_mdt_operating_system.os }} | {{ _dell_mdt_model.catalog_name }} | Attempt {{ _dell_mdt_download_retry }}" # noqa name[template]
      ansible.windows.win_file:
        path: "{{ _dell_mdt_download_path }}"
        state: directory
      changed_when: false

    - name: "Download Dell driver pack | {{ _dell_mdt_operating_system.os }} | {{ _dell_mdt_model.catalog_name }} | Attempt {{ _dell_mdt_download_retry }}" # noqa name[template]
      trippsc2.dell.win_dell_driver_pack:
        catalog_path: "{{ dell_mdt_temp_directory_path }}\\DriverPackCatalog.xml"
        download_path: "{{ _dell_mdt_download_path }}"
        os: "{{ _dell_mdt_operating_system.os }}"
        model: "{{ _dell_mdt_model.catalog_name }}"
        create_version_subdirectory: false
      register: _dell_mdt_download
      changed_when: false

    - name: "Extract EXE driver pack | {{ _dell_mdt_operating_system.os }} | {{ _dell_mdt_model.catalog_name }} | Attempt {{ _dell_mdt_download_retry }}" # noqa name[template]
      when:
        - _dell_mdt_download.driver_format == 'exe'
      ansible.windows.win_command: >-
        "{{ _dell_mdt_download.driver_pack_path }}" /s /e="{{ _dell_mdt_download_path }}"
      changed_when: false

    - name: "Set MDT base path variable | {{ _dell_mdt_operating_system.os }} | {{ _dell_mdt_model.catalog_name }} | Attempt {{ _dell_mdt_download_retry }}" # noqa name[template]
      ansible.builtin.set_fact:
        _dell_mdt_base_path: >-
          Out-of-Box Drivers\{{ _dell_mdt_operating_system.base_mdt_path }}\{{ _dell_mdt_model.mdt_name }}

    - name: "Set MDT version path variable | {{ _dell_mdt_operating_system.os }} | {{ _dell_mdt_model.catalog_name }} | Attempt {{ _dell_mdt_download_retry }}" # noqa name[template]
      ansible.builtin.set_fact:
        _dell_mdt_version_path: >-
          {{ _dell_mdt_base_path }}\{{ _dell_mdt_download.driver_pack_version }}

    - name: "Create version subdirectory | {{ _dell_mdt_operating_system.os }} | {{ _dell_mdt_model.catalog_name }} | Attempt {{ _dell_mdt_download_retry }}" # noqa name[template]
      trippsc2.mdt.directory:
        path: "{{ _dell_mdt_version_path }}"
        mdt_share_path: "{{ dell_mdt_share_path }}"
        state: present

    - name: "Import Dell driver pack | {{ _dell_mdt_operating_system.os }} | {{ _dell_mdt_model.catalog_name }} | Attempt {{ _dell_mdt_download_retry }}" # noqa name[template]
      trippsc2.mdt.import_drivers:
        source_paths:
          - "{{ _dell_mdt_download_path }}"
        path: "{{ _dell_mdt_version_path }}"
        mdt_share_path: "{{ dell_mdt_share_path }}"

    - name: "Get existing Dell driver pack directories | {{ _dell_mdt_operating_system.os }} | {{ _dell_mdt_model.catalog_name }} | Attempt {{ _dell_mdt_download_retry }}" # noqa name[template]
      trippsc2.mdt.directory_info:
        path: "{{ _dell_mdt_base_path }}"
        mdt_share_path: "{{ dell_mdt_share_path }}"
      register: _dell_mdt_versions

    - name: "Cleanup old driver packs | {{ _dell_mdt_operating_system.os }} | {{ _dell_mdt_model.catalog_name }} | Attempt {{ _dell_mdt_download_retry }}" # noqa name[template]
      loop: "{{ _dell_mdt_versions.directory.contents }}"
      when:
        - item.type == 'driver_folder'
        - _dell_mdt_download.driver_pack_version != item.name
      trippsc2.mdt.directory:
        path: "{{ _dell_mdt_base_path }}\\{{ item.name }}"
        mdt_share_path: "{{ dell_mdt_share_path }}"
        state: absent
      loop_control:
        label: "{{ item.name }}"

    - name: "Cleanup downloaded driver pack directory | {{ _dell_mdt_operating_system.os }} | {{ _dell_mdt_model.catalog_name }} | Attempt {{ _dell_mdt_download_retry }}" # noqa name[template]
      ansible.windows.win_file:
        path: "{{ _dell_mdt_download_path }}"
        state: absent
      changed_when: false
  rescue:
    - name: "Delete temporary directory | {{ _dell_mdt_operating_system.os }} | {{ _dell_mdt_model.catalog_name }} | Attempt {{ _dell_mdt_download_retry }}" # noqa name[template]
      ansible.windows.win_file:
        path: "{{ _dell_mdt_download_path }}"
        state: absent
      changed_when: false

    - name: "Fail if download retries exceed limit | {{ _dell_mdt_operating_system.os }} | {{ _dell_mdt_model.catalog_name }} | Attempt {{ _dell_mdt_download_retry }}" # noqa name[template]
      when: _dell_mdt_download_retry | int > 3
      ansible.builtin.fail:
        msg: "Failed to download Dell WinPE driver pack after {{ _dell_mdt_download_retry }} retries."

    - name: "Wait before retrying download | {{ _dell_mdt_operating_system.os }} | {{ _dell_mdt_model.catalog_name }} | Attempt {{ _dell_mdt_download_retry | int + 1 }}" # noqa name[template]
      ansible.builtin.pause:
        seconds: "{{ _dell_mdt_download_retry | int * 30 }}"

    - name: "Retry download | {{ _dell_mdt_operating_system.os }} | {{ _dell_mdt_model.catalog_name }} | Attempt {{ _dell_mdt_download_retry | int + 1 }}" # noqa name[template]
      ansible.builtin.include_tasks: win/attempt.yml
