---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: mdt_drivers
  description: This role manages Dell MDT drivers.

  license: MIT

  min_ansible_version: '2.16'

  platforms:
    - name: Windows
      versions:
        - '2025'
        - '2022'
        - '2019'

collections:
  - ansible.windows
  - community.windows
  - trippsc2.mdt
  - trippsc2.windows

dependencies:
  - role: trippsc2.windows.install_psgallery
