---
name: ansible-test
'on':
  workflow_call: {}
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
    paths:
      - galaxy.yml
      - plugins/modules/win_dell_driver_pack.ps1
      - plugins/modules/win_dell_driver_pack.py
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - plugins/modules/win_dell_driver_pack.ps1
      - plugins/modules/win_dell_driver_pack.py
defaults:
  run:
    working-directory: 'collections/ansible_collections/trippsc2/dell'
jobs:
  sanity:
    name: Run ansible-test
    runs-on:
      - self-hosted
      - linux
      - x64
    strategy:
      fail-fast: false
      matrix:
        ansible_version:
          - '2.18'
          - '2.17'
          - '2.16'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: 'collections/ansible_collections/trippsc2/dell'
      - name: Run Molecule tests
        run: |
          source ~/venv/ansible-test-${{ matrix.ansible_version }}/bin/activate
          ansible-test sanity -v --docker
          deactivate
