---
name: Generate Role Docs - mdt_drivers role
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs-mdt_drivers.yml
      - roles/mdt_drivers/.aar_doc.yml
      - roles/mdt_drivers/meta/argument_specs.yml
      - roles/mdt_drivers/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.dell'
jobs:
  docs:
    name: Generate mdt_drivers role documentation
    permissions:
      contents: write
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.dell'
      role_name: 'mdt_drivers'
