---
name: Molecule - mdt_drivers role
'on':
  workflow_call: {}
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/mdt_drivers/**
      - '!roles/mdt_drivers/.aar_doc.yml'
      - '!roles/mdt_drivers/README.md'
      - '!roles/mdt_drivers/meta/argument_specs.yml'
      - '!roles/mdt_drivers/meta/main.yml'
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/mdt_drivers/**
      - '!roles/mdt_drivers/.aar_doc.yml'
      - '!roles/mdt_drivers/README.md'
      - '!roles/mdt_drivers/meta/argument_specs.yml'
      - '!roles/mdt_drivers/meta/main.yml'
defaults:
  run:
    working-directory: 'trippsc2.dell'
jobs:
  molecule:
    name: Run Molecule tests
    uses: trippsoft/github-actions/.github/workflows/molecule.yml@main
    with:
      working_directory: 'trippsc2.dell'
      role_name: 'mdt_drivers'
      box: ${{ matrix.box }}
    strategy:
      fail-fast: false
      matrix:
        box:
          - w2025_cis
          - w2022_cis
          - w2019_cis
